### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Giuseppe-Mazzapica/Brain#2]
Packagist is quite picky and it's also good to know that there is a history to follow and to nail down packages by major, minor/feature and patch level version.

**Comment by Giuseppe-Mazzapica** [comment]
Tag releases have been added, alongside branch-alias in `composer.json`. 

Currently there is the 0.1.x series that will be tagged, and released under both "master" and "legacy" brances.

Reason is that as soon as possible (but it will take a while) I'll upgrade all Brain modules to 1.x version.

When that will happen 0.1.x version will stay on "legacy" , 1.x will be moved to "master". This precaution is because version 1.x will break backward compatibility and people who may have sites depending on old version of Brain and Brain modules can continue to use them without upgrade.

At the moment there is a pre-release v1.0.0-dev (branch-aliased into "in-progress" branch).

I think in a few weeks all modules should have at least a v1 pre-release so that will be possible to test how they work together.
